# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Hardware_final/Hardware_final.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hardware_final || ORIG_REF_NAME==Hardware_final} -quiet] -quiet

# IP: bd/Hardware_final/ip/Hardware_final_microblaze_0_0/Hardware_final_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hardware_final_microblaze_0_0 || ORIG_REF_NAME==Hardware_final_microblaze_0_0} -quiet] -quiet

# IP: bd/Hardware_final/ip/Hardware_final_dlmb_v10_0/Hardware_final_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hardware_final_dlmb_v10_0 || ORIG_REF_NAME==Hardware_final_dlmb_v10_0} -quiet] -quiet

# IP: bd/Hardware_final/ip/Hardware_final_ilmb_v10_0/Hardware_final_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hardware_final_ilmb_v10_0 || ORIG_REF_NAME==Hardware_final_ilmb_v10_0} -quiet] -quiet

# IP: bd/Hardware_final/ip/Hardware_final_dlmb_bram_if_cntlr_0/Hardware_final_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hardware_final_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==Hardware_final_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Hardware_final/ip/Hardware_final_ilmb_bram_if_cntlr_0/Hardware_final_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hardware_final_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==Hardware_final_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Hardware_final/ip/Hardware_final_lmb_bram_0/Hardware_final_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hardware_final_lmb_bram_0 || ORIG_REF_NAME==Hardware_final_lmb_bram_0} -quiet] -quiet

# IP: bd/Hardware_final/ip/Hardware_final_xbar_0/Hardware_final_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hardware_final_xbar_0 || ORIG_REF_NAME==Hardware_final_xbar_0} -quiet] -quiet

# IP: bd/Hardware_final/ip/Hardware_final_microblaze_0_axi_periph_0/Hardware_final_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hardware_final_microblaze_0_axi_periph_0 || ORIG_REF_NAME==Hardware_final_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/Hardware_final/ip/Hardware_final_microblaze_0_axi_intc_0/Hardware_final_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hardware_final_microblaze_0_axi_intc_0 || ORIG_REF_NAME==Hardware_final_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/Hardware_final/ip/Hardware_final_microblaze_0_xlconcat_0/Hardware_final_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hardware_final_microblaze_0_xlconcat_0 || ORIG_REF_NAME==Hardware_final_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/Hardware_final/ip/Hardware_final_mdm_1_0/Hardware_final_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hardware_final_mdm_1_0 || ORIG_REF_NAME==Hardware_final_mdm_1_0} -quiet] -quiet

# IP: bd/Hardware_final/ip/Hardware_final_clk_wiz_1_0/Hardware_final_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hardware_final_clk_wiz_1_0 || ORIG_REF_NAME==Hardware_final_clk_wiz_1_0} -quiet] -quiet

# IP: bd/Hardware_final/ip/Hardware_final_rst_clk_wiz_1_100M_0/Hardware_final_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hardware_final_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==Hardware_final_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/Hardware_final/ip/Hardware_final_axi_uartlite_0_0/Hardware_final_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hardware_final_axi_uartlite_0_0 || ORIG_REF_NAME==Hardware_final_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/Hardware_final/ip/Hardware_final_PmodACL_0_0/Hardware_final_PmodACL_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hardware_final_PmodACL_0_0 || ORIG_REF_NAME==Hardware_final_PmodACL_0_0} -quiet] -quiet

# IP: bd/Hardware_final/ip/Hardware_final_PmodBLE_0_0/Hardware_final_PmodBLE_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hardware_final_PmodBLE_0_0 || ORIG_REF_NAME==Hardware_final_PmodBLE_0_0} -quiet] -quiet

# IP: bd/Hardware_final/ip/Hardware_final_axi_iic_0_0/Hardware_final_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hardware_final_axi_iic_0_0 || ORIG_REF_NAME==Hardware_final_axi_iic_0_0} -quiet] -quiet

# IP: bd/Hardware_final/ip/Hardware_final_dlmb_bram_if_cntlr_1/Hardware_final_dlmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hardware_final_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==Hardware_final_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/Hardware_final/ip/Hardware_final_ilmb_bram_if_cntlr_1/Hardware_final_ilmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hardware_final_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==Hardware_final_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/Hardware_final/ip/Hardware_final_lmb_bram_1/Hardware_final_lmb_bram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hardware_final_lmb_bram_1 || ORIG_REF_NAME==Hardware_final_lmb_bram_1} -quiet] -quiet

# XDC: c:/HealthMonitorSystem/BlockDesign/Hardware_BlockDesign/Hardware_BlockDesign.gen/sources_1/bd/Hardware_final/Hardware_final_ooc.xdc
