# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/HealthMonitorSystem/BlockDesign/Hardware_BlockDesign/Hardware_BlockDesign.srcs/sources_1/bd/Hardware_final/ip/Hardware_final_ilmb_bram_if_cntlr_1/Hardware_final_ilmb_bram_if_cntlr_1.xci
# IP: The module: 'Hardware_final_ilmb_bram_if_cntlr_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/HealthMonitorSystem/BlockDesign/Hardware_BlockDesign/Hardware_BlockDesign.gen/sources_1/bd/Hardware_final/ip/Hardware_final_ilmb_bram_if_cntlr_1/Hardware_final_ilmb_bram_if_cntlr_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Hardware_final_ilmb_bram_if_cntlr_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/HealthMonitorSystem/BlockDesign/Hardware_BlockDesign/Hardware_BlockDesign.srcs/sources_1/bd/Hardware_final/ip/Hardware_final_ilmb_bram_if_cntlr_1/Hardware_final_ilmb_bram_if_cntlr_1.xci
# IP: The module: 'Hardware_final_ilmb_bram_if_cntlr_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/HealthMonitorSystem/BlockDesign/Hardware_BlockDesign/Hardware_BlockDesign.gen/sources_1/bd/Hardware_final/ip/Hardware_final_ilmb_bram_if_cntlr_1/Hardware_final_ilmb_bram_if_cntlr_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Hardware_final_ilmb_bram_if_cntlr_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
